### PR TITLE
Fetching data from API

### PR DESCRIPTION
**Pull request by AnisulMahmud**

### CODE REVIEW

**Comment by lassijjk** [comment]
Probably should add package-lock.json to gitignore.json and resolve other conflicts as well.

I changed the base branch to dev as we use dev for development and feature integration and only merge from dev to main whenever we have something to show.

**Comment by anhminh10a2hoa** [comment]
U need to resolve conflicts because I saw a lot of changes that already in the dev branch

**Comment by anhminh10a2hoa** [comment]
I think it's better if u have pagination for event list

**Comment by anhminh10a2hoa** [comment]
convert start time, end time, ... to be readable

**Comment by AnisulMahmud** [comment]
> U need to resolve conflicts because I saw a lot of changes that already in the dev branch

Some new line have to added here, that's why it sshowing same. The files are same.. But for my file, some line should be added as per as my commit. So conflict shouldn't be creat any problem.

**Review by anhminh10a2hoa — APPROVED** [review]

**Pull request merged**
